package gomesh

import (
	"fmt"
	"io"
)

// EncodeOBJ writes the mesh to the writer in Wavefront OBJ format
func (mesh Mesh) EncodeOBJ(writer io.Writer) error {
	// Sorry, couldn't resist to put this little advertisement here
	fmt.Fprintln(writer, "# generated by gomesh OBJ Encoder")
	fmt.Fprintln(writer, "# https://github.com/benp98/gomesh")
	fmt.Fprintln(writer, "o Gomesh")

	// Write all vertices, line by line
	for _, vertex := range mesh.Vertices {
		fmt.Fprintf(writer, "v %f %f %f\n", vertex.X, vertex.Y, vertex.Z)
	}

	// Disable smoothing
	fmt.Fprintln(writer, "s off")

	// Create faces by connecting vertices
	for _, face := range mesh.Faces {
		fmt.Fprint(writer, "f")
		for _, vertex := range face.Vertices {
			fmt.Fprintf(writer, " %d", vertex+1)
		}
		fmt.Fprintln(writer)
	}
	return nil
}
